### ISSUE TITLE
port to libratbag (suggestion)

### ISSUE THREAD

**Issue by bastianilso** [joelpet/logitech-mx-performance-dpi#1]
this is really nice little thing you have here - would love to see support for the mx performance in libratbag :)
https://github.com/libratbag/libratbag

**Comment by joelpet** [comment]
Good to hear you like it. All creds should go to Alexander Hofbauer who wrote the code – I only provided a simple Makefile for easier building. That also means I am not the one to port it to libratbag. I would suggest you reach out to the original author through that person's blog: http://derhofbauer.at/blog/blog/2012/08/28/logitech-performance-mx/. Best of luck!
